// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WG9jLMP3-0L6KEuAx8OZTeFBhQCDIjQ',
    appId: '1:709950791716:web:bad33d32130ede9d23f8b1',
    messagingSenderId: '709950791716',
    projectId: 'tinder-f7f18',
    authDomain: 'tinder-f7f18.firebaseapp.com',
    storageBucket: 'tinder-f7f18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQuFJI-uMy7yqNauxF0iwyWgCDtiHjG1s',
    appId: '1:709950791716:android:24c4708dba4a218523f8b1',
    messagingSenderId: '709950791716',
    projectId: 'tinder-f7f18',
    storageBucket: 'tinder-f7f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5dqzv5EM4MlrgIhO0w-XMXRZtwVkhTVo',
    appId: '1:709950791716:ios:6ed0c1e48626212c23f8b1',
    messagingSenderId: '709950791716',
    projectId: 'tinder-f7f18',
    storageBucket: 'tinder-f7f18.appspot.com',
    androidClientId: '709950791716-pjbnu07o38sn9t5i5m5tm7lprabus7tp.apps.googleusercontent.com',
    iosClientId: '709950791716-etj7mjhfrcrc1p0r3iplospdfs7p25vs.apps.googleusercontent.com',
    iosBundleId: 'com.convergeinnov.convergeimmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5dqzv5EM4MlrgIhO0w-XMXRZtwVkhTVo',
    appId: '1:709950791716:ios:6ed0c1e48626212c23f8b1',
    messagingSenderId: '709950791716',
    projectId: 'tinder-f7f18',
    storageBucket: 'tinder-f7f18.appspot.com',
    androidClientId: '709950791716-pjbnu07o38sn9t5i5m5tm7lprabus7tp.apps.googleusercontent.com',
    iosClientId: '709950791716-etj7mjhfrcrc1p0r3iplospdfs7p25vs.apps.googleusercontent.com',
    iosBundleId: 'com.convergeinnov.convergeimmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7WG9jLMP3-0L6KEuAx8OZTeFBhQCDIjQ',
    appId: '1:709950791716:web:039419dfa261cb0423f8b1',
    messagingSenderId: '709950791716',
    projectId: 'tinder-f7f18',
    authDomain: 'tinder-f7f18.firebaseapp.com',
    storageBucket: 'tinder-f7f18.appspot.com',
  );

}